baseURL = 'http://blog.fletcherporter.com/'
languageCode = 'en-us'
title = 'Fletcher Porter'
theme = 'fp'
sectionPagesMenu = 'main'

[params]
	[params.author]
	name = "Fletcher Porter"
	email = "me@fletcherporter.com"

[markup.goldmark.renderer]
unsafe = true
